/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package transformer.warranty.system;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.print.DocFlavor;
import javax.swing.ImageIcon;

/**
 *
 * @author Jatin
 */
public class ChangePasswordLogin extends javax.swing.JFrame {
    
    Connection con = null; Statement stmt = null; ResultSet rs = null;String email_id;
    RandomStringGenerator rsg = new RandomStringGenerator();
    MD5Generator pass = new MD5Generator();
    PopUp popobj = new PopUp();
    
   
    public ChangePasswordLogin(String id) {
        
        initComponents();
        SQLConnect sqlcon = new SQLConnect();
        con=sqlcon.sqlCon(con);
        email_id =id;
        jLabel18.setEnabled(false);
        jPasswordField2.setEnabled(false);
        jLabel19.setEnabled(false);
        jPasswordField3.setEnabled(false);
    }
    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        resendemail = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        ChangePassword = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 700));
        getContentPane().setLayout(null);

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Default_minimize.png"))); // NOI18N
        minimize.setText("jLabel7");
        minimize.setPreferredSize(new java.awt.Dimension(23, 15));
        getContentPane().add(minimize);
        minimize.setBounds(970, 4, 23, 15);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Default_close.png"))); // NOI18N
        close.setText("jLabel6");
        close.setPreferredSize(new java.awt.Dimension(23, 15));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(995, 4, 23, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Taskbar1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/boundary.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 25, 2, 675);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/boundary.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1022, 25, 2, 675);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Horizontal_boundary.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(2, 698, 1020, 2);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Untitled-12_1.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 30, 70, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/shadowmask_1.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 24, 1024, 80);

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.darkGray);
        jLabel10.setText("If you requested a new password but didn't recieved your password-reset email:");
        jLabel10.setToolTipText("");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(270, 150, 489, 16);

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel11.setForeground(java.awt.Color.darkGray);
        jLabel11.setText("1. Check the spam or junk mail folder in your email account.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(270, 185, 366, 16);

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel12.setForeground(java.awt.Color.darkGray);
        jLabel12.setText("2. Try to reset your password again.");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(270, 210, 219, 16);

        resendemail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Resend_Email.png"))); // NOI18N
        resendemail.setToolTipText("");
        resendemail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resendemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resendemailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resendemailMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resendemailMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                resendemailMouseReleased(evt);
            }
        });
        getContentPane().add(resendemail);
        resendemail.setBounds(480, 207, 140, 20);

        jLabel14.setFont(new java.awt.Font("Segoe UI Emoji", 0, 17)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 153));
        jLabel14.setText("Recieved Password");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(320, 360, 160, 19);

        jPasswordField1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 17)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(153, 0, 153));
        jPasswordField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jPasswordField1CaretUpdate(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(520, 360, 160, 25);

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 0, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 153));
        jLabel13.setText("Please enter below the password you recieved on your email.");
        jLabel13.setToolTipText("");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(270, 300, 464, 19);

        jLabel18.setFont(new java.awt.Font("Segoe UI Emoji", 0, 17)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 0, 153));
        jLabel18.setText("New Password");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(320, 395, 120, 19);

        jPasswordField2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 17)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(153, 0, 153));
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(520, 395, 160, 25);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Dotted_resend.png"))); // NOI18N
        jLabel9.setDoubleBuffered(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(265, 140, 500, 100);

        jLabel19.setFont(new java.awt.Font("Segoe UI Emoji", 0, 17)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 0, 153));
        jLabel19.setText("Confirm New Password");
        jLabel19.setDoubleBuffered(true);
        getContentPane().add(jLabel19);
        jLabel19.setBounds(320, 430, 190, 19);

        jPasswordField3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 17)); // NOI18N
        jPasswordField3.setForeground(new java.awt.Color(153, 0, 153));
        getContentPane().add(jPasswordField3);
        jPasswordField3.setBounds(520, 430, 160, 25);

        ChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/ChangePassword.png"))); // NOI18N
        ChangePassword.setText("jLabel21");
        ChangePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChangePasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChangePasswordMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ChangePasswordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ChangePasswordMouseReleased(evt);
            }
        });
        getContentPane().add(ChangePassword);
        ChangePassword.setBounds(520, 510, 160, 25);

        jLabel15.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel15.setForeground(java.awt.Color.darkGray);
        jLabel15.setText("* For security reasons, we ask you to change your password with a new one.");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(265, 625, 480, 16);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/login_taskbar_down.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(255, 615, 520, 34);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Sample.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(215, 90, 600, 600);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/login_pass.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(215, 90, 600, 600);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/login_pass.png"))); // NOI18N
        background.setText("jLabel5");
        getContentPane().add(background);
        background.setBounds(2, 80, 1020, 620);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resendemailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resendemailMouseEntered
        ImageIcon ISB=new ImageIcon(getClass().getResource("Resend_Email_hover.png"));
       resendemail.setIcon(ISB);
    }//GEN-LAST:event_resendemailMouseEntered

    private void resendemailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resendemailMouseExited
        ImageIcon ISB=new ImageIcon(getClass().getResource("Resend_Email.png"));
       resendemail.setIcon(ISB);
    }//GEN-LAST:event_resendemailMouseExited

    private void resendemailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resendemailMousePressed
        ImageIcon ISB=new ImageIcon(getClass().getResource("Resend_Email_hover.png"));
       resendemail.setIcon(ISB);
       
        
         try{
           stmt = con.createStatement();
                            String temp_password = rsg.generateRandomString(8);
                            String md5pass = pass.passwordgenerator(temp_password);
                            
                            stmt.executeUpdate("update login set password='"+md5pass+"' where email_id='"+email_id+"'");
                            EmailSender email = new EmailSender();
                            String[] to ={email_id};
                            if(email.sendMail("testingzebra@gmail.com","testmymail@21","You new password is : " + temp_password , to)){
                            popobj.setMessagelabel("Password sent successfully");
                            popobj.setVisible(true);
                            }
                            
                            else{
                                popobj.setMessagelabel("Some error occured");
                                popobj.setVisible(true);
                            }
                        }
                        catch(Exception e1){
                            popobj.setMessagelabel("Exception Occured : " + e1);
                             popobj.setVisible(true);
                        }
    }//GEN-LAST:event_resendemailMousePressed

    private void resendemailMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resendemailMouseReleased
        ImageIcon ISB=new ImageIcon(getClass().getResource("Resend_Email_hover.png"));
       resendemail.setIcon(ISB);
    }//GEN-LAST:event_resendemailMouseReleased

    private void ChangePasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordMouseEntered
        ImageIcon ISB=new ImageIcon(getClass().getResource("ChangePassword_hover.png"));
       ChangePassword.setIcon(ISB);
    }//GEN-LAST:event_ChangePasswordMouseEntered

    private void ChangePasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordMouseExited
        ImageIcon ISB=new ImageIcon(getClass().getResource("ChangePassword.png"));
       ChangePassword.setIcon(ISB);
    }//GEN-LAST:event_ChangePasswordMouseExited

    private void ChangePasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordMousePressed
        ImageIcon ISB=new ImageIcon(getClass().getResource("ChangePassword_pressed.png"));
       ChangePassword.setIcon(ISB);
    }//GEN-LAST:event_ChangePasswordMousePressed

    private void ChangePasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordMouseReleased
        ImageIcon ISB=new ImageIcon(getClass().getResource("ChangePassword_hover.png"));
       ChangePassword.setIcon(ISB);
    }//GEN-LAST:event_ChangePasswordMouseReleased

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
       ImageIcon ISB=new ImageIcon(getClass().getResource("Hover_close.png"));
       close.setIcon(ISB);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
       ImageIcon ISB=new ImageIcon(getClass().getResource("Default_close"));
       close.setIcon(ISB);
    }//GEN-LAST:event_closeMouseExited

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
       ImageIcon ISB=new ImageIcon(getClass().getResource("Pressed_close.png"));
       close.setIcon(ISB);
    }//GEN-LAST:event_closeMousePressed

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        ImageIcon II=new ImageIcon(getClass().getResource("Hover_close.png"));
        close.setIcon(II);
    }//GEN-LAST:event_closeMouseReleased

    private void jPasswordField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jPasswordField1CaretUpdate
       String password_temp = new String(jPasswordField1.getPassword());
        String password_md5 = pass.passwordgenerator(password_temp);       
        try{
        stmt = con.createStatement();
        rs= stmt.executeQuery("select * from login where password='"+password_md5+"' and email_id='"+email_id+"'");
        if(rs.next())
        {
            jLabel18.setEnabled(true);
            jPasswordField2.setEnabled(true);
            jLabel19.setEnabled(true);
            jPasswordField3.setEnabled(true);
        }
        }
        catch(Exception e1){
            popobj.setMessagelabel("Exception occured : " + e1);
            popobj.setVisible(true);
        }
    }//GEN-LAST:event_jPasswordField1CaretUpdate

    private void ChangePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordMouseClicked
        String password_temp = new String(jPasswordField1.getPassword());
        String newpassword = new String(jPasswordField2.getPassword());
        String confirmnewpassword = new String(jPasswordField3.getPassword());
        String password_md5 = pass.passwordgenerator(newpassword);
        try{
            stmt = con.createStatement();
            if(password_temp.equals(newpassword)||password_temp.equals(confirmnewpassword)){
                popobj.setMessagelabel("Old Password and New Password are same");
                popobj.setVisible(true);
                jPasswordField2.setText(null);
                jPasswordField3.setText(null);
            }
            else{
            if(newpassword.equals(confirmnewpassword)){
            stmt.executeUpdate("update login set password='"+password_md5+"' where email_id='"+email_id+"'");
            //Welcome welobj = new Welcome();
            //welobj.setVisible(true);
            this.dispose();
        }
            else{
                popobj.setMessagelabel("Passwords don't match");
                popobj.setVisible(true);
                jPasswordField2.setText(null);
                jPasswordField3.setText(null);
            }
        }
        }
        catch(Exception e1){
            popobj.setMessagelabel("Exception occured : " + e1);
            popobj.setVisible(true);
        }
        
    }//GEN-LAST:event_ChangePasswordMouseClicked

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new ChangePasswordLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChangePassword;
    private javax.swing.JLabel background;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel resendemail;
    // End of variables declaration//GEN-END:variables
}
