/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package transformer.warranty.system;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;

/**
 *
 * @author Jatin
 */
public class ForgotPassword extends javax.swing.JFrame {
Connection con = null; Statement stmt = null; ResultSet rs = null; String message = null;
String useremail; 
PopUp popobj = new PopUp();
RandomStringGenerator rsg = new RandomStringGenerator();
MD5Generator pass = new MD5Generator();



    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
       SQLConnect sqlcon = new SQLConnect();
        con=sqlcon.sqlCon(con);
    }
   

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        closebutton = new javax.swing.JLabel();
        taskbar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        submitbutton = new javax.swing.JLabel();
        resetbutton = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 350));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(650, 350));
        getContentPane().setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Logo.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(4, 0, 25, 25);

        closebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Default_close.png"))); // NOI18N
        closebutton.setText("jLabel6");
        closebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closebuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closebuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closebuttonMouseReleased(evt);
            }
        });
        getContentPane().add(closebutton);
        closebutton.setBounds(622, 5, 23, 15);

        taskbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Installation_Taskbar.png"))); // NOI18N
        taskbar.setText("jLabel1");
        getContentPane().add(taskbar);
        taskbar.setBounds(0, 0, 650, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Horizontal_boundary.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 347, 650, 3);

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Get back into your account");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(105, 40, 440, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("We can help you reset your password. First, enter your E-mail id.");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(65, 90, 520, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setText("E-mail Id");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(65, 170, 70, 30);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(270, 170, 300, 30);

        submitbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Submit.png"))); // NOI18N
        submitbutton.setText("jLabel5");
        submitbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                submitbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                submitbuttonMouseReleased(evt);
            }
        });
        getContentPane().add(submitbutton);
        submitbutton.setBounds(270, 270, 80, 25);

        resetbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Reset.png"))); // NOI18N
        resetbutton.setText("jLabel6");
        resetbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                resetbuttonMouseReleased(evt);
            }
        });
        getContentPane().add(resetbutton);
        resetbutton.setBounds(400, 270, 80, 25);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/InstallationBackkground.png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 25, 650, 322);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void submitbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitbuttonMouseEntered
        ImageIcon II=new ImageIcon(getClass().getResource("Submit_hover.png"));
         submitbutton.setIcon(II);
    }//GEN-LAST:event_submitbuttonMouseEntered

    private void submitbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitbuttonMouseExited
        ImageIcon II=new ImageIcon(getClass().getResource("Submit.png"));
         submitbutton.setIcon(II);
    }//GEN-LAST:event_submitbuttonMouseExited

    private void submitbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitbuttonMousePressed
        ImageIcon II=new ImageIcon(getClass().getResource("Submit_pressed.png"));
         submitbutton.setIcon(II);
    }//GEN-LAST:event_submitbuttonMousePressed

    private void submitbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitbuttonMouseReleased
        ImageIcon II=new ImageIcon(getClass().getResource("Submit.png"));
         submitbutton.setIcon(II);
    }//GEN-LAST:event_submitbuttonMouseReleased

    private void resetbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetbuttonMouseEntered
       ImageIcon II=new ImageIcon(getClass().getResource("Reset_hover.png"));
         resetbutton.setIcon(II);
    }//GEN-LAST:event_resetbuttonMouseEntered

    private void resetbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetbuttonMouseExited
        ImageIcon II=new ImageIcon(getClass().getResource("Reset.png"));
         resetbutton.setIcon(II);
    }//GEN-LAST:event_resetbuttonMouseExited

    private void resetbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetbuttonMousePressed
        ImageIcon II=new ImageIcon(getClass().getResource("Reset_pressed.png"));
         resetbutton.setIcon(II);
    }//GEN-LAST:event_resetbuttonMousePressed

    private void resetbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetbuttonMouseReleased
        ImageIcon II=new ImageIcon(getClass().getResource("Reset.png"));
         resetbutton.setIcon(II);
    }//GEN-LAST:event_resetbuttonMouseReleased

    private void closebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseClicked
        this.dispose();
    }//GEN-LAST:event_closebuttonMouseClicked

    private void closebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseEntered
        ImageIcon II=new ImageIcon(getClass().getResource("Hover_close.png"));
         closebutton.setIcon(II);
    }//GEN-LAST:event_closebuttonMouseEntered

    private void closebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseExited
        ImageIcon II=new ImageIcon(getClass().getResource("Default_close.png"));
        closebutton.setIcon(II);
    }//GEN-LAST:event_closebuttonMouseExited

    private void closebuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMousePressed
         ImageIcon II=new ImageIcon(getClass().getResource("Pressed_close.png"));
       closebutton.setIcon(II);
    }//GEN-LAST:event_closebuttonMousePressed

    private void closebuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseReleased
       ImageIcon II=new ImageIcon(getClass().getResource("Hover_close.png"));
        closebutton.setIcon(II);
    }//GEN-LAST:event_closebuttonMouseReleased

    private void resetbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetbuttonMouseClicked
        email.setText(null);
    }//GEN-LAST:event_resetbuttonMouseClicked

    private void submitbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitbuttonMouseClicked
        useremail = email.getText();
        if(evt.getSource()==submitbutton){    
            if(useremail.equals("")||useremail==null){
                popobj.setMessagelabel("Please enter you e-mail id");
                popobj.setVisible(true);
            }
            else{
                try{
                    stmt = con.createStatement();
                    rs = stmt.executeQuery("select * from login where email_id = '"+useremail+"'");
                    
                   if(rs.next()){
                        try{
                            String temp_password = rsg.generateRandomString(8);
                            String md5pass = pass.passwordgenerator(temp_password);                            
                            stmt.executeUpdate("update login set password='"+md5pass+"' where email_id='"+useremail+"'");
                            EmailSender email = new EmailSender();
                            String[] to ={useremail};
                            if(email.sendMail("testingzebra@gmail.com","testmymail@21","You new password is : " + temp_password , to)){
                           
                                //ChangePasswordLogin cp1 = new ChangePasswordLogin(useremail);
                            
                            ChangePasswordLogin cpl = new ChangePasswordLogin(useremail);
                            cpl.setVisible(true);
                            this.dispose();
                        }
                            else{
                                popobj.setMessagelabel("Some error occured");
                                popobj.setVisible(true);
                            
                        }}
                        catch(Exception e1){
                             popobj.setMessagelabel("Exception occured : " + e1);
                              popobj.setVisible(true);
                        }
                   }
                   else{
                       popobj.setMessagelabel("E-mail Id does not exist");
                        popobj.setVisible(true);
                   }
                }
                catch(Exception e1){
                    popobj.setMessagelabel("Exception Occured : " + e1);
                    popobj.setVisible(true);
                    System.out.println(e1);
                }
            }
        }
    }//GEN-LAST:event_submitbuttonMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel closebutton;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel resetbutton;
    private javax.swing.JLabel submitbutton;
    private javax.swing.JLabel taskbar;
    // End of variables declaration//GEN-END:variables
}
