/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package transformer.warranty.system;

import javax.swing.ImageIcon;

/**
 *
 * @author garima
 */
public class HelpPopup5 extends javax.swing.JFrame {

  /* public void slideshow1()
    {
         new Thread()
        {
            @Override
            public void run()
            {
                try
                {
                    Search.setVisible(true);
                    Search.setEnabled(true);
                }
                catch(Exception e)
                {
                    
                }
            }
        }.start();
    }  */
   
    public HelpPopup5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Search1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Deletehelp1 = new javax.swing.JLabel();
        Edithelp1 = new javax.swing.JLabel();
        Searchhelp1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Editpanel = new javax.swing.JPanel();
        Back = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Searchpanel = new javax.swing.JPanel();
        Back1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Deletepanel = new javax.swing.JPanel();
        Back2 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 420));
        setUndecorated(true);
        getContentPane().setLayout(null);

        Search1.setMaximumSize(new java.awt.Dimension(650, 420));
        Search1.setMinimumSize(new java.awt.Dimension(650, 420));
        Search1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Working with Records");
        Search1.add(jLabel4);
        jLabel4.setBounds(250, 4, 140, 20);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Default_close.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        Search1.add(jLabel13);
        jLabel13.setBounds(620, 5, 23, 15);

        Deletehelp1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Deletehelp1.setForeground(new java.awt.Color(153, 0, 153));
        Deletehelp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Deletehelp.png"))); // NOI18N
        Deletehelp1.setMaximumSize(new java.awt.Dimension(547, 20));
        Deletehelp1.setMinimumSize(new java.awt.Dimension(547, 20));
        Deletehelp1.setPreferredSize(new java.awt.Dimension(547, 20));
        Deletehelp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Deletehelp1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Deletehelp1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Deletehelp1MousePressed(evt);
            }
        });
        Search1.add(Deletehelp1);
        Deletehelp1.setBounds(60, 230, 90, 30);

        Edithelp1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Edithelp1.setForeground(new java.awt.Color(153, 0, 153));
        Edithelp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Edithelp.png"))); // NOI18N
        Edithelp1.setMaximumSize(new java.awt.Dimension(547, 20));
        Edithelp1.setMinimumSize(new java.awt.Dimension(547, 20));
        Edithelp1.setPreferredSize(new java.awt.Dimension(547, 20));
        Edithelp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Edithelp1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Edithelp1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Edithelp1MousePressed(evt);
            }
        });
        Search1.add(Edithelp1);
        Edithelp1.setBounds(60, 190, 50, 30);

        Searchhelp1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Searchhelp1.setForeground(new java.awt.Color(153, 0, 153));
        Searchhelp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Searchhelp.png"))); // NOI18N
        Searchhelp1.setMaximumSize(new java.awt.Dimension(547, 20));
        Searchhelp1.setMinimumSize(new java.awt.Dimension(547, 20));
        Searchhelp1.setPreferredSize(new java.awt.Dimension(547, 20));
        Searchhelp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Searchhelp1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Searchhelp1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Searchhelp1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Searchhelp1MousePressed(evt);
            }
        });
        Search1.add(Searchhelp1);
        Searchhelp1.setBounds(60, 150, 90, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 153));
        jLabel8.setText("Working with Records");
        Search1.add(jLabel8);
        jLabel8.setBounds(30, 70, 240, 26);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Installation_Taskbar.png"))); // NOI18N
        jLabel9.setText("jLabel2");
        jLabel9.setMaximumSize(new java.awt.Dimension(650, 25));
        jLabel9.setMinimumSize(new java.awt.Dimension(650, 25));
        jLabel9.setPreferredSize(new java.awt.Dimension(650, 25));
        jLabel9.setRequestFocusEnabled(false);
        Search1.add(jLabel9);
        jLabel9.setBounds(0, 0, 650, 25);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/InstallationBackkground.png"))); // NOI18N
        Search1.add(jLabel10);
        jLabel10.setBounds(0, 0, 650, 420);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/InstallationBackkground.png"))); // NOI18N
        Search1.add(jLabel11);
        jLabel11.setBounds(0, 0, 650, 420);

        getContentPane().add(Search1);
        Search1.setBounds(0, 0, 650, 420);

        Editpanel.setMaximumSize(new java.awt.Dimension(650, 420));
        Editpanel.setMinimumSize(new java.awt.Dimension(650, 420));
        Editpanel.setLayout(null);

        Back.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Back.setForeground(new java.awt.Color(153, 0, 153));
        Back.setText("Back");
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.setDoubleBuffered(true);
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackMousePressed(evt);
            }
        });
        Editpanel.add(Back);
        Back.setBounds(30, 40, 32, 20);

        jLabel34.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(153, 0, 153));
        jLabel34.setText("Record-->Edit.Enter the Specification Number of the tranformer of which you want the editing");
        Editpanel.add(jLabel34);
        jLabel34.setBounds(50, 150, 590, 30);

        jLabel35.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(153, 0, 153));
        jLabel35.setText("all the details will appear on the window . Now you can edit only the enabled fields.");
        Editpanel.add(jLabel35);
        jLabel35.setBounds(50, 180, 590, 30);

        jLabel33.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(153, 0, 153));
        jLabel33.setText("Edit window enables you to edit the details of the transformer. You can access this window as ");
        Editpanel.add(jLabel33);
        jLabel33.setBounds(50, 120, 590, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Working with Records");
        Editpanel.add(jLabel7);
        jLabel7.setBounds(250, 4, 140, 20);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Default_close.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel23MousePressed(evt);
            }
        });
        Editpanel.add(jLabel23);
        jLabel23.setBounds(620, 5, 23, 15);

        jLabel24.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 0, 153));
        jLabel24.setText("Edit Records");
        Editpanel.add(jLabel24);
        jLabel24.setBounds(30, 70, 240, 26);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Installation_Taskbar.png"))); // NOI18N
        jLabel25.setText("jLabel2");
        jLabel25.setMaximumSize(new java.awt.Dimension(650, 25));
        jLabel25.setMinimumSize(new java.awt.Dimension(650, 25));
        jLabel25.setPreferredSize(new java.awt.Dimension(650, 25));
        jLabel25.setRequestFocusEnabled(false);
        Editpanel.add(jLabel25);
        jLabel25.setBounds(0, 0, 650, 25);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/InstallationBackkground.png"))); // NOI18N
        Editpanel.add(jLabel27);
        jLabel27.setBounds(0, 0, 650, 420);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/InstallationBackkground.png"))); // NOI18N
        Editpanel.add(jLabel26);
        jLabel26.setBounds(0, 0, 650, 420);

        getContentPane().add(Editpanel);
        Editpanel.setBounds(0, 0, 650, 420);

        Searchpanel.setMaximumSize(new java.awt.Dimension(650, 420));
        Searchpanel.setMinimumSize(new java.awt.Dimension(650, 420));
        Searchpanel.setLayout(null);

        Back1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Back1.setForeground(new java.awt.Color(153, 0, 153));
        Back1.setText("Back");
        Back1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Back1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Back1MousePressed(evt);
            }
        });
        Searchpanel.add(Back1);
        Back1.setBounds(30, 40, 32, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Working with Records");
        Searchpanel.add(jLabel5);
        jLabel5.setBounds(250, 4, 140, 20);

        jLabel32.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(153, 0, 153));
        jLabel32.setText("from the large tables.");
        jLabel32.setMaximumSize(new java.awt.Dimension(547, 16));
        jLabel32.setMinimumSize(new java.awt.Dimension(547, 16));
        jLabel32.setPreferredSize(new java.awt.Dimension(547, 16));
        Searchpanel.add(jLabel32);
        jLabel32.setBounds(50, 240, 590, 30);

        jLabel29.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 0, 153));
        jLabel29.setText("Search window by choosing the Search from the Menu Bar.");
        jLabel29.setMaximumSize(new java.awt.Dimension(547, 16));
        jLabel29.setMinimumSize(new java.awt.Dimension(547, 16));
        jLabel29.setPreferredSize(new java.awt.Dimension(547, 16));
        Searchpanel.add(jLabel29);
        jLabel29.setBounds(50, 150, 590, 30);

        jLabel28.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 0, 153));
        jLabel28.setText("Search window is used when you want to search record of a specific transformer. You can access");
        Searchpanel.add(jLabel28);
        jLabel28.setBounds(50, 120, 590, 30);

        jLabel31.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(153, 0, 153));
        jLabel31.setText("Date of installation of the transformer. Using the Search the time wastage in finding the records ");
        jLabel31.setMaximumSize(new java.awt.Dimension(547, 16));
        jLabel31.setMinimumSize(new java.awt.Dimension(547, 16));
        jLabel31.setPreferredSize(new java.awt.Dimension(547, 16));
        Searchpanel.add(jLabel31);
        jLabel31.setBounds(50, 210, 590, 30);

        jLabel30.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(153, 0, 153));
        jLabel30.setText("You can search the record by entering its Specification Number or The buyers name or");
        jLabel30.setMaximumSize(new java.awt.Dimension(547, 16));
        jLabel30.setMinimumSize(new java.awt.Dimension(547, 16));
        jLabel30.setPreferredSize(new java.awt.Dimension(547, 16));
        Searchpanel.add(jLabel30);
        jLabel30.setBounds(50, 180, 590, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Default_close.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
        });
        Searchpanel.add(jLabel14);
        jLabel14.setBounds(620, 5, 23, 15);

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 153));
        jLabel12.setText("Search");
        Searchpanel.add(jLabel12);
        jLabel12.setBounds(30, 70, 240, 26);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Installation_Taskbar.png"))); // NOI18N
        jLabel15.setText("jLabel2");
        jLabel15.setMaximumSize(new java.awt.Dimension(650, 25));
        jLabel15.setMinimumSize(new java.awt.Dimension(650, 25));
        jLabel15.setPreferredSize(new java.awt.Dimension(650, 25));
        jLabel15.setRequestFocusEnabled(false);
        Searchpanel.add(jLabel15);
        jLabel15.setBounds(0, 0, 650, 25);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/InstallationBackkground.png"))); // NOI18N
        Searchpanel.add(jLabel16);
        jLabel16.setBounds(0, 0, 650, 420);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/InstallationBackkground.png"))); // NOI18N
        Searchpanel.add(jLabel17);
        jLabel17.setBounds(0, 0, 650, 420);

        getContentPane().add(Searchpanel);
        Searchpanel.setBounds(0, 0, 650, 420);

        Deletepanel.setMaximumSize(new java.awt.Dimension(650, 420));
        Deletepanel.setMinimumSize(new java.awt.Dimension(650, 420));
        Deletepanel.setLayout(null);

        Back2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Back2.setForeground(new java.awt.Color(153, 0, 153));
        Back2.setText("Back");
        Back2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Back2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Back2MousePressed(evt);
            }
        });
        Deletepanel.add(Back2);
        Back2.setBounds(30, 40, 32, 20);

        jLabel37.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(153, 0, 153));
        jLabel37.setText("You can open the delete window as: Records-->Delete.");
        Deletepanel.add(jLabel37);
        jLabel37.setBounds(50, 150, 590, 30);

        jLabel38.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(153, 0, 153));
        jLabel38.setText("To delete the record enter the Specification Number and press Delete, the record will be deleted.");
        Deletepanel.add(jLabel38);
        jLabel38.setBounds(50, 180, 590, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Working with Records");
        Deletepanel.add(jLabel6);
        jLabel6.setBounds(250, 4, 140, 20);

        jLabel36.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(153, 0, 153));
        jLabel36.setText("Delete is used whenever you want to delete the specific record from the database permanently.");
        Deletepanel.add(jLabel36);
        jLabel36.setBounds(50, 120, 590, 30);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Default_close.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel18MousePressed(evt);
            }
        });
        Deletepanel.add(jLabel18);
        jLabel18.setBounds(620, 5, 23, 15);

        jLabel19.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 0, 153));
        jLabel19.setText("Delete Records");
        Deletepanel.add(jLabel19);
        jLabel19.setBounds(30, 70, 240, 26);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Installation_Taskbar.png"))); // NOI18N
        jLabel20.setText("jLabel2");
        jLabel20.setMaximumSize(new java.awt.Dimension(650, 25));
        jLabel20.setMinimumSize(new java.awt.Dimension(650, 25));
        jLabel20.setPreferredSize(new java.awt.Dimension(650, 25));
        jLabel20.setRequestFocusEnabled(false);
        Deletepanel.add(jLabel20);
        jLabel20.setBounds(0, 0, 650, 25);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/InstallationBackkground.png"))); // NOI18N
        Deletepanel.add(jLabel21);
        jLabel21.setBounds(0, 0, 650, 420);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/InstallationBackkground.png"))); // NOI18N
        Deletepanel.add(jLabel22);
        jLabel22.setBounds(0, 0, 650, 420);

        getContentPane().add(Deletepanel);
        Deletepanel.setBounds(0, 0, 650, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
          this.dispose();
    }//GEN-LAST:event_jLabel13MousePressed

    private void Deletehelp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Deletehelp1MouseEntered
         ImageIcon ISB=new ImageIcon(getClass().getResource("Deletehelp_hover.png"));
       Deletehelp1.setIcon(ISB);
    }//GEN-LAST:event_Deletehelp1MouseEntered

    private void Deletehelp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Deletehelp1MouseExited
        ImageIcon ISB=new ImageIcon(getClass().getResource("Deletehelp.png"));
       Deletehelp1.setIcon(ISB);
    }//GEN-LAST:event_Deletehelp1MouseExited

    private void Edithelp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edithelp1MouseEntered
        ImageIcon ISB=new ImageIcon(getClass().getResource("Edithelp_hover.png"));
       Edithelp1.setIcon(ISB);
    }//GEN-LAST:event_Edithelp1MouseEntered

    private void Edithelp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edithelp1MouseExited
        ImageIcon ISB=new ImageIcon(getClass().getResource("Edithelp.png"));
       Edithelp1.setIcon(ISB);
    }//GEN-LAST:event_Edithelp1MouseExited

    private void Edithelp1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edithelp1MousePressed
       ImageIcon ISB=new ImageIcon(getClass().getResource("Edithelp_hover.png"));
       Edithelp1.setIcon(ISB);
        Searchpanel.setEnabled(false);
       Searchpanel.setVisible(false);
       Search1.setEnabled(false);
       Search1.setVisible(false);
        Deletepanel.setEnabled(false);
       Deletepanel.setVisible(false);
       Editpanel.setEnabled(true);
       Editpanel.setVisible(true);
    }//GEN-LAST:event_Edithelp1MousePressed

    private void Searchhelp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Searchhelp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Searchhelp1MouseClicked

    private void Searchhelp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Searchhelp1MouseEntered
        ImageIcon ISB=new ImageIcon(getClass().getResource("Searchhelp_hover.png"));
       Searchhelp1.setIcon(ISB);
    }//GEN-LAST:event_Searchhelp1MouseEntered

    private void Searchhelp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Searchhelp1MouseExited
        ImageIcon ISB=new ImageIcon(getClass().getResource("Searchhelp.png"));
       Searchhelp1.setIcon(ISB);
    }//GEN-LAST:event_Searchhelp1MouseExited

    private void Searchhelp1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Searchhelp1MousePressed
         ImageIcon ISB=new ImageIcon(getClass().getResource("Searchhelp_hover.png"));
       Searchhelp1.setIcon(ISB);
       Searchpanel.setEnabled(true);
       Searchpanel.setVisible(true);
       Search1.setEnabled(false);
       Search1.setVisible(false);
        Deletepanel.setEnabled(false);
       Deletepanel.setVisible(false);
       Editpanel.setEnabled(false);
       Editpanel.setVisible(false);
    }//GEN-LAST:event_Searchhelp1MousePressed

    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
      this.dispose();
    }//GEN-LAST:event_jLabel14MousePressed

    private void jLabel18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MousePressed
       this.dispose();
    }//GEN-LAST:event_jLabel18MousePressed

    private void Deletehelp1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Deletehelp1MousePressed
       ImageIcon ISB=new ImageIcon(getClass().getResource("Deleteuse_hover.png"));
       Deletehelp1.setIcon(ISB);
        Searchpanel.setEnabled(false);
       Searchpanel.setVisible(false);
       Deletepanel.setEnabled(true);
       Deletepanel.setVisible(true);
       Search1.setEnabled(false);
       Search1.setVisible(false);
         Editpanel.setEnabled(false);
       Editpanel.setVisible(false);
    }//GEN-LAST:event_Deletehelp1MousePressed

    private void jLabel23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MousePressed
        this.dispose();
    }//GEN-LAST:event_jLabel23MousePressed

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BackMouseEntered

    private void BackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMousePressed
        Searchpanel.setEnabled(false);
       Searchpanel.setVisible(false);
       Search1.setEnabled(true);
       Search1.setVisible(true);
        Deletepanel.setEnabled(false);
       Deletepanel.setVisible(false);
       Editpanel.setEnabled(false);
       Editpanel.setVisible(false);
    }//GEN-LAST:event_BackMousePressed

    private void Back1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Back1MouseEntered

    private void Back1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back1MousePressed
          Searchpanel.setEnabled(false);
       Searchpanel.setVisible(false);
       Search1.setEnabled(true);
       Search1.setVisible(true);
        Deletepanel.setEnabled(false);
       Deletepanel.setVisible(false);
       Editpanel.setEnabled(false);
       Editpanel.setVisible(false);
    }//GEN-LAST:event_Back1MousePressed

    private void Back2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back2MouseEntered
        
    }//GEN-LAST:event_Back2MouseEntered

    private void Back2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back2MousePressed
       Searchpanel.setEnabled(false);
       Searchpanel.setVisible(false);
       Search1.setEnabled(true);
       Search1.setVisible(true);
        Deletepanel.setEnabled(false);
       Deletepanel.setVisible(false);
       Editpanel.setEnabled(false);
       Editpanel.setVisible(false);
    }//GEN-LAST:event_Back2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpPopup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpPopup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpPopup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpPopup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpPopup1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Back1;
    private javax.swing.JLabel Back2;
    private javax.swing.JLabel Deletehelp1;
    private javax.swing.JPanel Deletepanel;
    private javax.swing.JLabel Edithelp1;
    private javax.swing.JPanel Editpanel;
    private javax.swing.JPanel Search1;
    private javax.swing.JLabel Searchhelp1;
    private javax.swing.JPanel Searchpanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
