/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package transformer.warranty.system;

import javax.swing.ImageIcon;

/**
 *
 * @author garima
 */
public class HelpPopup6 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public HelpPopup6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        Profile = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Deleteuser = new javax.swing.JLabel();
        Newuser = new javax.swing.JLabel();
        Yourprofile = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Yourprofilepanel = new javax.swing.JPanel();
        Back = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Newuserpanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Back1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        Deleteuserpanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Back2 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/InstallationBackkground.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 420));
        setUndecorated(true);
        getContentPane().setLayout(null);

        Profile.setMaximumSize(new java.awt.Dimension(650, 420));
        Profile.setMinimumSize(new java.awt.Dimension(650, 420));
        Profile.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Using the Profile");
        Profile.add(jLabel4);
        jLabel4.setBounds(250, 4, 140, 20);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Default_close.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        Profile.add(jLabel13);
        jLabel13.setBounds(620, 5, 23, 15);

        Deleteuser.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Deleteuser.setForeground(new java.awt.Color(153, 0, 153));
        Deleteuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Deleteuse.png"))); // NOI18N
        Deleteuser.setMaximumSize(new java.awt.Dimension(547, 20));
        Deleteuser.setMinimumSize(new java.awt.Dimension(547, 20));
        Deleteuser.setPreferredSize(new java.awt.Dimension(547, 20));
        Deleteuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteuserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteuserMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DeleteuserMousePressed(evt);
            }
        });
        Profile.add(Deleteuser);
        Deleteuser.setBounds(60, 230, 90, 30);

        Newuser.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Newuser.setForeground(new java.awt.Color(153, 0, 153));
        Newuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Newuserhelp.png"))); // NOI18N
        Newuser.setMaximumSize(new java.awt.Dimension(547, 20));
        Newuser.setMinimumSize(new java.awt.Dimension(547, 20));
        Newuser.setPreferredSize(new java.awt.Dimension(547, 20));
        Newuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewuserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewuserMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NewuserMousePressed(evt);
            }
        });
        Profile.add(Newuser);
        Newuser.setBounds(60, 190, 70, 30);

        Yourprofile.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Yourprofile.setForeground(new java.awt.Color(153, 0, 153));
        Yourprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Yourprofilethelp.png"))); // NOI18N
        Yourprofile.setMaximumSize(new java.awt.Dimension(547, 20));
        Yourprofile.setMinimumSize(new java.awt.Dimension(547, 20));
        Yourprofile.setPreferredSize(new java.awt.Dimension(547, 20));
        Yourprofile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YourprofileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                YourprofileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                YourprofileMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                YourprofileMousePressed(evt);
            }
        });
        Profile.add(Yourprofile);
        Yourprofile.setBounds(60, 150, 90, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 153));
        jLabel8.setText("Using the Profile");
        Profile.add(jLabel8);
        jLabel8.setBounds(30, 70, 240, 26);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Installation_Taskbar.png"))); // NOI18N
        jLabel9.setText("jLabel2");
        jLabel9.setMaximumSize(new java.awt.Dimension(650, 25));
        jLabel9.setMinimumSize(new java.awt.Dimension(650, 25));
        jLabel9.setPreferredSize(new java.awt.Dimension(650, 25));
        jLabel9.setRequestFocusEnabled(false);
        Profile.add(jLabel9);
        jLabel9.setBounds(0, 0, 650, 25);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/InstallationBackkground.png"))); // NOI18N
        Profile.add(jLabel11);
        jLabel11.setBounds(0, 0, 650, 420);

        getContentPane().add(Profile);
        Profile.setBounds(0, 0, 650, 420);

        Yourprofilepanel.setMaximumSize(new java.awt.Dimension(650, 420));
        Yourprofilepanel.setMinimumSize(new java.awt.Dimension(650, 420));
        Yourprofilepanel.setLayout(null);

        Back.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Back.setForeground(new java.awt.Color(153, 0, 153));
        Back.setText("Back");
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackMousePressed(evt);
            }
        });
        Yourprofilepanel.add(Back);
        Back.setBounds(30, 40, 32, 18);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Using the Profile");
        Yourprofilepanel.add(jLabel7);
        jLabel7.setBounds(250, 4, 140, 20);

        jLabel19.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 0, 153));
        jLabel19.setText("New password field and Confirm password field will be enabled.");
        Yourprofilepanel.add(jLabel19);
        jLabel19.setBounds(40, 230, 580, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 0, 153));
        jLabel18.setText("When you click Edit it will ask you your old password, if the password is correct then only the ");
        Yourprofilepanel.add(jLabel18);
        jLabel18.setBounds(40, 200, 580, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 0, 153));
        jLabel15.setText("Your Profile window enables one's to edit their passwords of their profile. You can open this ");
        Yourprofilepanel.add(jLabel15);
        jLabel15.setBounds(40, 110, 580, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 0, 153));
        jLabel16.setText("window as Profile-->Your Profile. ");
        Yourprofilepanel.add(jLabel16);
        jLabel16.setBounds(40, 140, 580, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 0, 153));
        jLabel17.setText("On the Your Profile window fill your username and click Edit to edit your password.");
        Yourprofilepanel.add(jLabel17);
        jLabel17.setBounds(40, 170, 580, 30);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Default_close.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel23MousePressed(evt);
            }
        });
        Yourprofilepanel.add(jLabel23);
        jLabel23.setBounds(620, 5, 23, 15);

        jLabel24.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 0, 153));
        jLabel24.setText("Your Profile");
        Yourprofilepanel.add(jLabel24);
        jLabel24.setBounds(30, 70, 240, 26);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Installation_Taskbar.png"))); // NOI18N
        jLabel25.setText("jLabel2");
        jLabel25.setMaximumSize(new java.awt.Dimension(650, 25));
        jLabel25.setMinimumSize(new java.awt.Dimension(650, 25));
        jLabel25.setPreferredSize(new java.awt.Dimension(650, 25));
        jLabel25.setRequestFocusEnabled(false);
        Yourprofilepanel.add(jLabel25);
        jLabel25.setBounds(0, 0, 650, 25);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/InstallationBackkground.png"))); // NOI18N
        Yourprofilepanel.add(jLabel26);
        jLabel26.setBounds(0, 0, 650, 420);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/InstallationBackkground.png"))); // NOI18N
        Yourprofilepanel.add(jLabel27);
        jLabel27.setBounds(0, 0, 650, 420);

        getContentPane().add(Yourprofilepanel);
        Yourprofilepanel.setBounds(0, 0, 650, 420);

        Newuserpanel.setMaximumSize(new java.awt.Dimension(650, 420));
        Newuserpanel.setMinimumSize(new java.awt.Dimension(650, 420));
        Newuserpanel.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Using the Profile");
        Newuserpanel.add(jLabel12);
        jLabel12.setBounds(250, 4, 140, 20);

        Back1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Back1.setForeground(new java.awt.Color(153, 0, 153));
        Back1.setText("Back");
        Back1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Back1MousePressed(evt);
            }
        });
        Newuserpanel.add(Back1);
        Back1.setBounds(30, 40, 32, 18);

        jLabel21.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 0, 153));
        jLabel21.setText("The New User window allows you the admin to create new user as per the requirements.");
        Newuserpanel.add(jLabel21);
        jLabel21.setBounds(40, 110, 580, 30);

        jLabel20.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 0, 153));
        jLabel20.setText("You can access this window as Profile-->New User. ");
        Newuserpanel.add(jLabel20);
        jLabel20.setBounds(40, 140, 580, 30);

        jLabel22.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 0, 153));
        jLabel22.setText("There can be multiple number of subadmins profile but you can have only one admin profile");
        Newuserpanel.add(jLabel22);
        jLabel22.setBounds(40, 170, 580, 30);

        jLabel39.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(153, 0, 153));
        Newuserpanel.add(jLabel39);
        jLabel39.setBounds(40, 230, 580, 30);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Default_close.png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel28MousePressed(evt);
            }
        });
        Newuserpanel.add(jLabel28);
        jLabel28.setBounds(620, 5, 23, 15);

        jLabel29.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 0, 153));
        jLabel29.setText("New user");
        Newuserpanel.add(jLabel29);
        jLabel29.setBounds(30, 70, 240, 26);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Installation_Taskbar.png"))); // NOI18N
        jLabel30.setText("jLabel2");
        jLabel30.setMaximumSize(new java.awt.Dimension(650, 25));
        jLabel30.setMinimumSize(new java.awt.Dimension(650, 25));
        jLabel30.setPreferredSize(new java.awt.Dimension(650, 25));
        jLabel30.setRequestFocusEnabled(false);
        Newuserpanel.add(jLabel30);
        jLabel30.setBounds(0, 0, 650, 25);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/InstallationBackkground.png"))); // NOI18N
        Newuserpanel.add(jLabel31);
        jLabel31.setBounds(0, 0, 650, 420);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/InstallationBackkground.png"))); // NOI18N
        Newuserpanel.add(jLabel32);
        jLabel32.setBounds(0, 0, 650, 420);

        jLabel38.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(153, 0, 153));
        jLabel38.setText("When you click Edit it will ask you your old password, if the password is correct then only the ");
        Newuserpanel.add(jLabel38);
        jLabel38.setBounds(40, 200, 580, 30);

        getContentPane().add(Newuserpanel);
        Newuserpanel.setBounds(0, 0, 650, 420);

        Deleteuserpanel.setMaximumSize(new java.awt.Dimension(650, 420));
        Deleteuserpanel.setMinimumSize(new java.awt.Dimension(650, 420));
        Deleteuserpanel.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Using the Profile");
        Deleteuserpanel.add(jLabel14);
        jLabel14.setBounds(250, 4, 140, 20);

        Back2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Back2.setForeground(new java.awt.Color(153, 0, 153));
        Back2.setText("Back");
        Back2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Back2MousePressed(evt);
            }
        });
        Deleteuserpanel.add(Back2);
        Back2.setBounds(30, 40, 32, 18);

        jLabel41.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(153, 0, 153));
        jLabel41.setText("You can access this window as Profile-->Delete User. ");
        Deleteuserpanel.add(jLabel41);
        jLabel41.setBounds(40, 140, 580, 30);

        jLabel42.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(153, 0, 153));
        jLabel42.setText("One cannot delete the profile of admin.");
        Deleteuserpanel.add(jLabel42);
        jLabel42.setBounds(40, 170, 580, 30);

        jLabel40.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(153, 0, 153));
        jLabel40.setText("The Delete User window allows you the admin to delete user as per the requirements.");
        Deleteuserpanel.add(jLabel40);
        jLabel40.setBounds(40, 110, 580, 30);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Default_close.png"))); // NOI18N
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel33MousePressed(evt);
            }
        });
        Deleteuserpanel.add(jLabel33);
        jLabel33.setBounds(620, 5, 23, 15);

        jLabel34.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(153, 0, 153));
        jLabel34.setText("Delete User");
        Deleteuserpanel.add(jLabel34);
        jLabel34.setBounds(30, 70, 240, 26);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/Installation_Taskbar.png"))); // NOI18N
        jLabel35.setText("jLabel2");
        jLabel35.setMaximumSize(new java.awt.Dimension(650, 25));
        jLabel35.setMinimumSize(new java.awt.Dimension(650, 25));
        jLabel35.setPreferredSize(new java.awt.Dimension(650, 25));
        jLabel35.setRequestFocusEnabled(false);
        Deleteuserpanel.add(jLabel35);
        jLabel35.setBounds(0, 0, 650, 25);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/InstallationBackkground.png"))); // NOI18N
        Deleteuserpanel.add(jLabel36);
        jLabel36.setBounds(0, 0, 650, 420);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transformer/warranty/system/InstallationBackkground.png"))); // NOI18N
        Deleteuserpanel.add(jLabel37);
        jLabel37.setBounds(0, 0, 650, 420);

        getContentPane().add(Deleteuserpanel);
        Deleteuserpanel.setBounds(0, 0, 650, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        this.dispose();
    }//GEN-LAST:event_jLabel13MousePressed

    private void DeleteuserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteuserMouseEntered
        ImageIcon ISB=new ImageIcon(getClass().getResource("Deleteuse_hover.png"));
        Deleteuser.setIcon(ISB);
    }//GEN-LAST:event_DeleteuserMouseEntered

    private void DeleteuserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteuserMouseExited
        ImageIcon ISB=new ImageIcon(getClass().getResource("Deleteuse.png"));
        Deleteuser.setIcon(ISB);
    }//GEN-LAST:event_DeleteuserMouseExited

    private void DeleteuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteuserMousePressed
        ImageIcon ISB=new ImageIcon(getClass().getResource("Deleteuse_hover.png"));
        Deleteuser.setIcon(ISB);
        Yourprofilepanel.setEnabled(false);
       Yourprofilepanel.setVisible(false);
        Profile.setEnabled(false);
        Profile.setVisible(false);
         Newuserpanel.setEnabled(false);
         Newuserpanel.setVisible(false);
         Deleteuserpanel.setEnabled(true);
         Deleteuserpanel.setVisible(true);
         
    }//GEN-LAST:event_DeleteuserMousePressed

    private void NewuserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewuserMouseEntered
        ImageIcon ISB=new ImageIcon(getClass().getResource("Newuserhelp_hover.png"));
        Newuser.setIcon(ISB);
    }//GEN-LAST:event_NewuserMouseEntered

    private void NewuserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewuserMouseExited
        ImageIcon ISB=new ImageIcon(getClass().getResource("Newuserhelp.png"));
        Newuser.setIcon(ISB);
    }//GEN-LAST:event_NewuserMouseExited

    private void NewuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewuserMousePressed
        ImageIcon ISB=new ImageIcon(getClass().getResource("Edithelp_hover.png"));
        Newuser.setIcon(ISB);
        Yourprofilepanel.setEnabled(false);
       Yourprofilepanel.setVisible(false);
        Profile.setEnabled(false);
        Profile.setVisible(false);
        Newuserpanel.setEnabled(true);
         Newuserpanel.setVisible(true);
            Deleteuserpanel.setEnabled(false);
         Deleteuserpanel.setVisible(false);
        
    }//GEN-LAST:event_NewuserMousePressed

    private void YourprofileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YourprofileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_YourprofileMouseClicked

    private void YourprofileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YourprofileMouseEntered
        ImageIcon ISB=new ImageIcon(getClass().getResource("Yourprofilethelp_hover.png"));
        Yourprofile.setIcon(ISB);
    }//GEN-LAST:event_YourprofileMouseEntered

    private void YourprofileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YourprofileMouseExited
        ImageIcon ISB=new ImageIcon(getClass().getResource("Yourprofilethelp.png"));
        Yourprofile.setIcon(ISB);
    }//GEN-LAST:event_YourprofileMouseExited

    private void YourprofileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YourprofileMousePressed
        ImageIcon ISB=new ImageIcon(getClass().getResource("Searchhelp_hover.png"));
        Yourprofile.setIcon(ISB);
       Yourprofilepanel.setEnabled(true);
       Yourprofilepanel.setVisible(true);
        Profile.setEnabled(false);
        Profile.setVisible(false);
     Newuserpanel.setEnabled(false);
         Newuserpanel.setVisible(false);
            Deleteuserpanel.setEnabled(false);
         Deleteuserpanel.setVisible(false);
    }//GEN-LAST:event_YourprofileMousePressed

    private void jLabel23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MousePressed
        this.dispose();
    }//GEN-LAST:event_jLabel23MousePressed

    private void jLabel28MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MousePressed
        this.dispose();
    }//GEN-LAST:event_jLabel28MousePressed

    private void jLabel33MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MousePressed
        this.dispose();
    }//GEN-LAST:event_jLabel33MousePressed

    private void BackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMousePressed
  
       Yourprofilepanel.setEnabled(false);
       Yourprofilepanel.setVisible(false);
        Profile.setEnabled(true);
        Profile.setVisible(true);
     Newuserpanel.setEnabled(false);
         Newuserpanel.setVisible(false);
            Deleteuserpanel.setEnabled(false);
         Deleteuserpanel.setVisible(false);
    }//GEN-LAST:event_BackMousePressed

    private void Back1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back1MousePressed
     
       Yourprofilepanel.setEnabled(false);
       Yourprofilepanel.setVisible(false);
        Profile.setEnabled(true);
        Profile.setVisible(true);
     Newuserpanel.setEnabled(false);
         Newuserpanel.setVisible(false);
            Deleteuserpanel.setEnabled(false);
         Deleteuserpanel.setVisible(false);
    }//GEN-LAST:event_Back1MousePressed

    private void Back2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back2MousePressed
      
       Yourprofilepanel.setEnabled(false);
       Yourprofilepanel.setVisible(false);
        Profile.setEnabled(true);
        Profile.setVisible(true);
     Newuserpanel.setEnabled(false);
         Newuserpanel.setVisible(false);
            Deleteuserpanel.setEnabled(false);
         Deleteuserpanel.setVisible(false);
    }//GEN-LAST:event_Back2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpPopup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpPopup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpPopup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpPopup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpPopup1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Back1;
    private javax.swing.JLabel Back2;
    private javax.swing.JLabel Deleteuser;
    private javax.swing.JPanel Deleteuserpanel;
    private javax.swing.JLabel Newuser;
    private javax.swing.JPanel Newuserpanel;
    private javax.swing.JPanel Profile;
    private javax.swing.JLabel Yourprofile;
    private javax.swing.JPanel Yourprofilepanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
