/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package transformer.warranty.system;

import static transformer.warranty.system.InstallationFrame.WarehouseYear;

/**
 *
 * @author Anugrah
 */
public class TransformerWarrantySystem 
{
    static int date=0,month=0,year=0;
    public static void main(String[] args) {
       TransformerWarrantySystem t1=new TransformerWarrantySystem();
     t1.Cal_day(16,8,2015,16,9,2016);//Input date of installation and date of complain
      t1.Cal_left(622,12,12,2016);//Input days left and date of reinstallation
      t1.caldate(29,4, 2015);
   //   System.out.println("\n"+date+":"+month+":"+year);
    //  t1.Cal_day(29,8,2014,date,month,year);
      t1.caldate1(1, 8, 2015,36);
      t1.caldate2(28,8,2013,42);
      t1.small(4,6,2018,31,5,2015);
      t1.caldate3(25, 8, 2018);
    }
    void Cal_day(int d1,int m1,int y1,int d2,int m2,int y2)
    {
        int j=d1;
        int i=m1,d = 0,k,r;
       // int a=m2;
      
       if(i==m2&&y1==y2)
       {
           d=d2-d1;
           System.out.println("\n"+d);
       }
       else
       {   
           if((y1%4)==0)
           {
                if(i==1||i==3||i==5||i==7||i==8||i==10||i==12)
                {
                   d=31-j+1; i=i+1;  
                }
               else
                {
                    if(i==2)
                    {
                        d=29-j+1;i=i+1;
                    }
                    else
                    {
                        d=30-j+1;i=i+1;
                    }
               }
            }
           else
           {   
               if(i==1||i==3||i==5||i==7||i==8||i==10||i==12)
                {
                   d=31-j+1; i=i+1;  
                }
               else
                {
                    if(i==2)
                    {
                        d=28-j+1;i=i+1;
                    }
                    else
                    {
                        d=30-j+1;i=i+1;
                    }
               }
           }
      // if(m1!=m2&&y1!=y2)
            for(int y=y1;y<=y2;y++)
            {   
                if((y%4)==0)
                {
                    if(i>m2&&y<y2)
                    {   
                        for(k=i;k<=12;k++)
                        {  
                            if(k==1||k==3||k==5||k==7||k==8||k==10||k==12)
                            {
                                d=d+31;  
                            }
                            else
                            {
                                if(k==2)
                                {
                                d=d+29;
                                }
                                else
                                {
                                d=d+30;
                                }
                            }   
                        }
                      i=1;
                    }
                   else
                   {   
                       if(i<=m2&&y<y2)
                        {
                            for(k=i;k<=12;k++)
                            {  
                                if(k==1||k==3||k==5||k==7||k==8||k==10||k==12)
                                {
                                    d=d+31;  
                                }
                               else
                               {
                                    if(k==2)
                                    {
                                     d=d+29;
                                    }
                                    else
                                    {
                                     d=d+30;
                                    }
                                }    
                            }i=1;
                        }
                       else
                       {
                            for(k=i;k<m2;k++)
                            {  
                                if(k==1||k==3||k==5||k==7||k==8||k==10||k==12)
                                {
                                   d=d+31;  
                                }
                               else
                               {
                                   if(k==2)
                                   {
                                      d=d+29;
                                    }
                                   else
                                   {
                                      d=d+30;
                                    }
                               }   
                            } 
                        }   
                    }
                }
               else
               {
                   if(i>m2&&y<y2)
                   {   
                       for(k=i;k<=12;k++)
                       {  
                            if(k==1||k==3||k==5||k==7||k==8||k==10||k==12)
                           {
                               d=d+31;  
                            }
                           else
                           {
                               if(k==2)
                               {
                                  d=d+28;
                                }
                               else
                               {
                                  d=d+30;
                                }
                            }   
                        }
                     i=1;
                    }
                   else
                   {   
                       if(i<=m2&&y<y2)
                       {
                            for(k=i;k<=12;k++)
                           {  
                                if(k==1||k==3||k==5||k==7||k==8||k==10||k==12)
                                {
                                   d=d+31;  
                                }
                               else
                               {
                                    if(k==2)
                                   {
                                      d=d+28;
                                    }
                                   else
                                   {
                                      d=d+30;
                                    }
                                }
                            }i=1;
                        }
                       else
                       {
                           for(k=i;k<m2;k++)
                           {  
                               if(k==1||k==3||k==5||k==7||k==8||k==10||k==12)
                               {
                                  d=d+31;  
                                }
                               else
                               {
                                   if(k==2)
                                   {
                                      d=d+28;
                                    }
                                   else
                                   {
                                      d=d+30;
                                    }
                                }
                            } 
                        }   
                    }   
                }
            }
           d=d+d2;
           System.out.println("\n"+d);
        }
    }
    void Cal_left(int d,int d1,int m,int y)
    {
       int k=m,a=d1;
       if(k==1||k==3||k==5||k==7||k==8||k==10||k==12)
       {
           a=31-a;
           if(a<d)
           {
               if(a==0)
               {
                   d1=1;m++;d=0;
               }
               else
               {
                    d=d-a-1;m++;
               }  
            }
           else
           {
               if(d==1)
               {
                   d=a-d;
                   d1=31-d;
                   d=0;
                }
               else
               {
                   d=a-d;
                   d1=31-d-1;
                   d=0; 
                }
            }
        }
       else
       {
           if(k==2)
           {
               if(y%4==0)
               {
                   a=29-a;
                   if(a<d)
                   {
                      if(a==0)
                       {
                           d1=1;m++;d=0;
                       }
                       else
                       {
                            d=d-a-1;m++;
                       }  
                    }
                   else
                   {
                      if(d==1)
                       {
                           d=a-d;
                           d1=29-d;
                           d=0;
                       }
                       else
                       {
                           d=a-d;
                           d1=29-d-1;
                           d=0; 
                       }
                    } 
               }
               else
               {
                   a=28-a;
                   if(a<d)
                   {
                      if(a==0)
                       {
                           d1=1;m++;d=0;
                       }
                       else
                       {
                            d=d-a-1;m++;
                       }
                    }
                   else
                   {
                      if(d==1)
                       {
                           d=a-d;
                           d1=28-d;
                           d=0;
                       }
                       else
                       {
                           d=a-d;
                           d1=28-d-1;
                           d=0; 
                       }
                    }
               }
            }
           else
           {
               a=30-a;
               if(a<d)
               {
                  if(a==0)
                   {
                       d1=1;m++;d=0;
                    }
                   else
                   {
                        d=d-a-1;m++;
                    }  
               }
               else
               {
                  if(d==1)
                   {
                       d=a-d;
                       d1=30-d;
                       d=0;
                   }
                   else
                   {
                       d=a-d;
                       d1=30-d-1;
                       d=0; 
                    }
                }
            }
        }
       if(m>12){
           k=1;y++;
       }
       else
       {
           k=m;
       }
        while(d>0)
        {
           if((y%4)==0)
           {
               if((k==0||k==1||k==3||k==5||k==7||k==8||k==10||k==12)&&(d>=31))
               {
                   d=d-31;k++;
               }
               else
               {
                   if((k==2)&&(d>=29))
                   {
                       d=d-29;k++;
                   }
                   else
                   {    
                       if((k==4||k==6||k==9||k==11)&&(d>=30))
                       {
                           d=d-30;k++;  
                        }
                       else
                       {
                           d1=d;d=0;
                        }
                    }
               }
               if(k>12)
               {
                    y++;k=1;
                }
           }
           else
           {
               if((k==0||k==1||k==3||k==5||k==7||k==8||k==10||k==12)&&(d>=31))
               {
                   d=d-31;k++;
                }
               else
               {
                   if((k==2)&&(d>=28))
                   {
                       d=d-28;k++;
                    }
                   else
                   {
                       if((k==4||k==6||k==9||k==11)&&(d>=30))
                       {
                           d=d-30;k++;  
                        }
                       else
                       {
                           d1=d;d=0;
                        }
                    }    
                } 
               if(k>12)
               {
                   y++;k=1;
                }
               
            }    
        }
        System.out.print(d1+":"+k+":"+y);
    }  
    public void caldate(int d,int m,int y)
    {
        int d1 = 0,m1,y1 = y;
        if((d>1)&&(d<=29))
        {
            d1=d-1;m1=m+6;
            if(m1>12)
            {
                m1=m1-12;y1=y+1;
            }  
        }
        else
        {
            if((d==30)&&(m==8)&&(((y+1)%4)==0))
            {
                d1=29;m1=2;y1=y+1;
            }
            else
            {
               if((d==30)&&(m==8)&&(((y+1)%4)!=0))
               {
                d1=28;m1=2;y1=y+1;
               }
               else
               {
                  if((d==31)&&(m==8)&&(((y+1)%4)==0))
                    {
                      d1=29;m1=2;y1=y+1;
                    }
                    else
                    {
                        if((d==31)&&(m==8)&&(((y+1)%4)!=0))
                        {
                            d1=28;m1=2;y1=y+1;
                        }
                        else
                        {
                            if(d==1)
                            {
                               m1=m+6;
                               if(m1>12)
                               {
                                   m1=m1-12;
                                   if(m1==1||m1==2||m1==3||m1==4||m1==6||m1==8||m1==9||m1==11)
                                   {
                                       if(m1==3&&(((y+1)%4)==0))
                                       {
                                           d1=29;m1=2;y1=y+1;
                                       }
                                       else
                                       {
                                           if(m1==3&&(((y+1)%4)!=0))
                                           {
                                           d1=28;m1=2;y1=y+1;
                                           }
                                           else
                                           {
                                               if(m1==1)
                                               {
                                                   d1=31;m1=12;
                                               }
                                               else
                                               {
                                                d1=31;m1=m1-1;y1=y+1;
                                               }
                                           }
                                       }
                                    }
                                   else
                                   {
                                   d1=30;m1=m1-1;y1=y+1;
                                   }
                               }
                               else
                               {
                                   if(m1==1||m1==2||m1==3||m1==4||m1==6||m1==8||m1==9||m1==11)
                                   {
                                       if(m1==3&&(((y+1)%4)==0))
                                       {
                                           d1=29;m1=2;
                                       }
                                       else
                                       {
                                           if(m1==3&&(((y+1)%4)!=0))
                                           {
                                           d1=28;m1=2;
                                           }
                                           else
                                           {
                                               d1=31;m1=m1-1;
                                           }
                                       }
                                    }
                                   else
                                   {
                                   d1=30;m1=m1-1;
                                    }
                                }
                            }
                           else
                            {     
                                d1=d-1;m1=m+6;
                                if(m1>12)
                                {
                                   m1=m1-12;y1=y+1;
                                }
                            }
                        }
                    }
               }
            }
           
        }
        //date=d1;month=m1;year=y1;
          System.out.println("\n"+d1+":"+m1+":"+y1);
    }
    public void caldate1(int d,int m,int y,int mtw)
    {
        int d1=0,m1 = 0,y1 = y;
        if((d>1)&&(d<=31))
        {
            d1=d-1;
            m1=m;y1=y1+(mtw/12);
        }
        else
        {
            if(d==1)
           {
               while(mtw!=0)
               {
                   if((mtw/12)!=1)
                   {
                       d1=d;m1=m;y1=y1+1;mtw=mtw-12;
                   }
                   else
                   {
                       if(m1==1||m1==2||m1==3||m1==4||m1==6||m1==8||m1==9||m1==11)
                       {
                           if(m1==3&&(((y1+1)%4)==0))
                           {
                               d1=29;m1=2;y1=y1+1;
                            }
                           else
                           {
                               if(m1==3&&(((y1+1)%4)!=0))
                               {
                                   d1=28;m1=2;y1=y1+1;
                                }
                               else
                               {
                                   if(m1==1)
                                   {
                                       d1=31;m1=12;
                                    }
                                   else
                                   {
                                       d1=31;m1=m1-1;y1=y1+1;
                                    }
                                }
                            }
                        }
                       else
                       {
                           d1=30;m1=m1-1;y1=y1+1;
                        }
                       mtw=0;
                   }
               }
           }    
                        
        }
        System.out.println("\n"+d1+":"+m1+":"+y1);
    }
    public void caldate2(int d,int m,int y,int mtw)
    {
        int d1=d,m1=m;int y1=y;//mtw=mtw-6;
        while(mtw!=0)
        {
            if(mtw>12)
           {
                mtw=mtw-12;
                y1=y1+1;
            }
            else
            {
               if((d>1)&&(d<=29))
               {
                   d1=d1-1;m1=m1+6;
                   if(m1>12)
                   {
                        m1=m1-12;y1=y1+1;
                    }  
                }
               else
               {
                   if((d==30)&&(m==8)&&(((y1+1)%4)==0))
                   {
                       d1=29;m1=2;y1=y1+1;
                    }
                   else
                   {
                       if((d==30)&&(m==8)&&(((y1+1)%4)!=0))
                       {
                            d1=28;m1=2;y1=y1+1;
                        }
                       else
                       {
                            if((d==31)&&(m==8)&&(((y1+1)%4)==0))
                           {
                               d1=29;m1=2;y1=y1+1;
                            }
                           else
                           {
                               if((d==31)&&(m==8)&&(((y1+1)%4)!=0))
                               {
                                    d1=28;m1=2;y1=y1+1;
                                }
                               else
                               {
                                    if(d==1)
                                   {
                                        m1=m1+6;
                                       if(m1>12)
                                       {
                                           m1=m1-12;
                                           if(m1==1||m1==2||m1==3||m1==4||m1==6||m1==8||m1==9||m1==11)
                                           {
                                               if(m1==3&&(((y1+1)%4)==0))
                                               {
                                                   d1=29;m1=2;y1=y+1;
                                                }
                                               else
                                               {
                                                   if(m1==3&&(((y1+1)%4)!=0))
                                                    {
                                                       d1=28;m1=2;y1=y1+1;
                                                    }
                                                   else
                                                   {
                                                       if(m1==1)
                                                       {
                                                           d1=31;m1=12;
                                                        }
                                                       else
                                                       {
                                                           d1=31;m1=m1-1;y1=y1+1;
                                                        }
                                                    }
                                                }
                                            }
                                       else
                                       {
                                           d1=30;m1=m1-1;y1=y1+1;
                                        }
                                    }
                                   else
                                   {
                                       if(m1==1||m1==2||m1==3||m1==4||m1==6||m1==8||m1==9||m1==11)
                                       {
                                           if(m1==3&&(((y1+1)%4)==0))
                                           {
                                               d1=29;m1=2;
                                            }
                                           else
                                           {
                                               if(m1==3&&(((y1+1)%4)!=0))
                                               {
                                                   d1=28;m1=2;
                                                }
                                               else
                                               {
                                                   d1=31;m1=m1-1;
                                                }
                                            }
                                        }
                                       else
                                       {
                                           d1=30;m1=m1-1;
                                        }
                                    }
                                }
                               else
                               {     
                                   d1=d-1;m1=m+6;
                                   if(m1>12)
                                   {
                                   m1=m1-12;y1=y1+1;
                                   }
                                }
                            }
                        }
                    }
                }
                          
            }
            mtw=0; 
         }
        }System.out.println("\n"+d1+":"+m1+":"+y1);
    }
    public void small(int d1,int m1,int y1,int d2,int m2,int y2)
    {
       int expirydate,expirymonth,expiryyear;
        if(y2<=y1)
                   {
                       if(y2==y1)
                       {
                           if(m2<=m1)
                           {
                               if(m2==m1)
                               {
                                   if(d2<=d1)
                                   {
                                       if(d2==d1)
                                       {
                                           expirydate=d1; 
                                           expirymonth=m1;
                                           expiryyear=y1;
                                           System.out.println("\n"+expirydate+":"+expirymonth+":"+expiryyear);
                                       }
                                       else
                                       {
                                          expirydate=d2;
                                          expirymonth=m2; 
                                          expiryyear=y2;
                                           System.out.println("\n"+expirydate+":"+expirymonth+":"+expiryyear);
                                       }
                                   }
                                   else
                                   {
                                       expirydate=d1; 
                                       expirymonth=m1;
                                       expiryyear=y1;
                                        System.out.println("\n"+expirydate+":"+expirymonth+":"+expiryyear);
                                   }
                               }
                               else
                               {
                                   expirydate=d2;
                                   expirymonth=m2; 
                                   expiryyear=y2;
                                    System.out.println("\n"+expirydate+":"+expirymonth+":"+expiryyear);
                               }
                           }
                           else
                           {
                               expirydate=d1; 
                               expirymonth=m1;
                               expiryyear=y1;
                                System.out.println("\n"+expirydate+":"+expirymonth+":"+expiryyear);
                           }
                        }
                       else
                       {
                           expirydate=d2;
                           expirymonth=m2; 
                           expiryyear=y2;
                            System.out.println("\n"+expirydate+":"+expirymonth+":"+expiryyear);
                       }
                    }
                   else
                   {
                       expirydate=d1; 
                       expirymonth=m1;
                       expiryyear=y1;
                        System.out.println("\n"+expirydate+":"+expirymonth+":"+expiryyear);
                   }
    }
    public void caldate3(int d,int m,int y)
    {
        int d1 =0,m1=0,y1 = y;
        if((d>=1)&&(d<=27))
        {
            d1=d+1;m1=m-6;
            if(m1<0)
            {
                m1=12+m1;y1=y-1;
            }
            else
            {
                if(m1==0)
                {
                   m1=12;y1=y-1;
                }
            }
        }
        else
        {
            if((d==30||d==28||d==29)&&(m==8)&&(((y)%4)==0))
            {
                d1=29;m1=2;
            }
            else
            {
               if((d==30||d==28||d==29)&&(m==8)&&(((y)%4)!=0))
               {
                d1=28;m1=2;
               }
               else
               {
                  if((d==31)&&(m==8)&&(((y)%4)==0))
                    {
                      d1=1;m1=3;
                    }
                    else
                    {
                        if((d==31)&&(m==8)&&(((y)%4)!=0))
                        {
                            d1=1;m1=3;
                        }
                        else
                        {
                            if(d==31||d==30)
                            {
                               m1=m-6;
                               if(m1<0)
                               {
                                   m1=12+m1;
                                   if(d==30)
                                   {
                                       if(m1==9||m1==11)
                                       {
                                           d1=1;m1=m1+1;y1=y-1;
                                       }
                                       else
                                       {
                                          d1=31;y1=y-1;
                                       }
                                   }
                                   else
                                   {
                                       if(m1==11||m1==9||m1==7)
                                       {
                                           d1=1;m1=m1+1;y1=y-1;
                                       }
                                       else
                                       {
                                           d1=1;m1=m1+1;y1=y-1;
                                       }
                                   }
                               }
                               else
                               {
                                   if(d==30)
                                   {
                                       if(m1==0)
                                       {
                                          d1=31;m1=12;y1=y-1; 
                                       }
                                       else
                                       {
                                           if(m1==6||m1==4)
                                           {
                                               d1=1;m1=m1+1;
                                           }
                                           else
                                           {
                                               if(m1==5||m1==3||m1==1)
                                               {
                                                   d1=31;
                                               }
                                           }
                                       }
                                    }
                                   else
                                   {
                                       if(m1==7||m1==8||m1==10||m1==12)
                                       {
                                           d1=1;m1=m1+1;
                                       }
                                       else
                                       {
                                           d1=1;m1=m1+1;
                                       }
                                   }
                                }
                            }
                           else
                            {     
                                m1=m-6;
                                if(m1<0)
                                {
                                   d1=d+1;m1=12+m1;y1=y-1;
                                }
                                else
                                {
                                    if(m1==0)
                                    {
                                       d1=d+1;m1=12;y1=y-1;;
                                    }
                                    else
                                    {
                                       d1=d+1;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        //date=d1;month=m1;year=y1;
          System.out.println("\n"+d1+":"+m1+":"+y1);
    }
    
}
    
